//! Generate runnable ApiWright and k6 suites from a parsed OpenAPI document.

use std::path::{Path, PathBuf};

use serde_json::{json, Value};

use crate::model::{AssertionDef, AuthConfig, Check, Method};
use crate::openapi::{contract_checks, example_from_schema, operation_to_request, ParsedSpec};

use super::{migrate_request, AssertionDocument};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OpenApiSuiteKind {
    Contract,
    Api,
    K6,
}

impl OpenApiSuiteKind {
    pub fn folder(self) -> &'static str {
        match self {
            Self::Contract => "contract",
            Self::Api => "api",
            Self::K6 => "performance",
        }
    }

    fn label(self) -> &'static str {
        match self {
            Self::Contract => "contract",
            Self::Api => "api",
            Self::K6 => "k6",
        }
    }
}

#[derive(Debug, Clone)]
pub struct GeneratedOpenApiSuite {
    pub directory: PathBuf,
    pub files: usize,
    pub requests: usize,
    pub warnings: Vec<String>,
}

/// Generate below `parent`. Existing generated suites are replaced, while an
/// unrelated non-empty folder is never deleted.
pub fn generate_openapi_suite(
    root: &Path,
    parent: &Path,
    spec: &ParsedSpec,
    kind: OpenApiSuiteKind,
) -> Result<GeneratedOpenApiSuite, String> {
    if !parent.is_dir() || !parent.starts_with(root) {
        return Err("generation target must be an existing project folder".to_string());
    }
    if spec.operations.is_empty() {
        return Err("OpenAPI spec contains no operations".to_string());
    }

    let directory = parent.join(kind.folder());
    prepare_directory(&directory, kind)?;

    let result = match kind {
        OpenApiSuiteKind::Contract | OpenApiSuiteKind::Api => {
            generate_forge_suite(root, &directory, spec, kind)
        }
        OpenApiSuiteKind::K6 => generate_k6_suite(&directory, spec),
    };
    if result.is_err() {
        let _ = std::fs::remove_dir_all(&directory);
    }
    result.map(|(files, requests, warnings)| GeneratedOpenApiSuite {
        directory,
        files,
        requests,
        warnings,
    })
}

fn prepare_directory(directory: &Path, kind: OpenApiSuiteKind) -> Result<(), String> {
    if directory.exists() {
        let marker = directory.join("manifest.json");
        let generated = std::fs::read_to_string(&marker)
            .ok()
            .and_then(|text| serde_json::from_str::<Value>(&text).ok())
            .is_some_and(|manifest| {
                manifest.get("generator").and_then(Value::as_str) == Some("forge-openapi")
                    && manifest.get("kind").and_then(Value::as_str) == Some(kind.label())
            });
        if !generated {
            return Err(format!(
                "{} already exists and was not generated by ApiWright",
                directory.display()
            ));
        }
        std::fs::remove_dir_all(directory)
            .map_err(|error| format!("cannot replace {}: {error}", directory.display()))?;
    }
    std::fs::create_dir_all(directory)
        .map_err(|error| format!("cannot create {}: {error}", directory.display()))
}

fn generate_forge_suite(
    root: &Path,
    directory: &Path,
    spec: &ParsedSpec,
    kind: OpenApiSuiteKind,
) -> Result<(usize, usize, Vec<String>), String> {
    let mut request_paths = Vec::with_capacity(spec.operations.len());
    let mut warnings = Vec::new();
    let mut files = 3;
    let base_url = base_url(spec);

    for operation in &spec.operations {
        let id = slug(&operation.id);
        let stem = format!("{}-{id}", operation.method.as_str().to_ascii_lowercase());
        let request_path = directory.join(format!("{stem}.request.json"));
        let mut request = operation_to_request(operation);
        request.auth = AuthConfig::None;
        request.url = request.url.replace("{{baseUrl}}", &base_url);
        for parameter in &mut request.params {
            parameter.kv.value = "1".to_string();
            parameter.kv.enabled = true;
        }
        for header in &mut request.headers {
            header.value = "value".to_string();
            header.enabled = true;
        }
        if let Some(content_type) = &operation.request_content_type {
            if !request
                .headers
                .iter()
                .any(|header| header.key.eq_ignore_ascii_case("content-type"))
            {
                request
                    .headers
                    .push(crate::model::KeyValue::new("Content-Type", content_type));
            }
        }

        let mut checks = contract_checks(operation, None);
        checks.retain(|check| match check {
            Check::JsonSchema { schema } if has_external_ref(schema) => {
                warnings.push(format!(
                    "{} {}: external response schema reference was not embedded",
                    operation.method, operation.path
                ));
                false
            }
            Check::StatusClass { .. } => {
                warnings.push(format!(
                    "{} {}: wildcard response status has no exact assertion",
                    operation.method, operation.path
                ));
                false
            }
            _ => true,
        });
        if kind == OpenApiSuiteKind::Api {
            checks.push(Check::ResponseTimeBelow { max_ms: 2_000 });
        }
        request.assertions = checks.into_iter().map(AssertionDef::from).collect();

        let mut document = migrate_request(&request, &operation.id)
            .map_err(|error| format!("cannot generate {}: {error}", operation.id))?;
        document.meta.tags.extend(operation.tags.clone());
        document
            .meta
            .tags
            .push(format!("generated-{}", kind.label()));
        let assertions = AssertionDocument::take_from_request(&mut document);
        write_json(&request_path, &document)?;
        files += 1;
        if !assertions.assertions.is_empty() {
            files += 1;
        }
        assertions.save_for_request(&request_path)?;
        request_paths.push(project_relative(root, &request_path)?);
    }

    let sequence = json!({
        "formatVersion": 1,
        "kind": "sequence",
        "meta": {
            "id": format!("generated-{}", kind.label()),
            "name": format!("Generated {} tests", kind.label())
        },
        "requests": request_paths,
    });
    write_json(
        &directory.join(format!("{}.sequence.json", kind.folder())),
        &sequence,
    )?;
    write_json(&directory.join("openapi.source.json"), &spec.raw)?;
    write_manifest(directory, spec, kind, &warnings)?;
    Ok((files, spec.operations.len(), warnings))
}

fn generate_k6_suite(
    directory: &Path,
    spec: &ParsedSpec,
) -> Result<(usize, usize, Vec<String>), String> {
    let operations = spec
        .operations
        .iter()
        .map(|operation| {
            let mut path = operation.path.clone();
            for parameter in &operation.path_params {
                path = path.replace(&format!("{{{parameter}}}"), "1");
            }
            let query = operation
                .query_params
                .iter()
                .filter(|(_, required)| *required)
                .map(|(name, _)| format!("{name}=1"))
                .collect::<Vec<_>>();
            if !query.is_empty() {
                path.push('?');
                path.push_str(&query.join("&"));
            }
            let body = operation.request_example.clone().or_else(|| {
                operation
                    .request_schema
                    .as_ref()
                    .map(|schema| example_from_schema(schema, 0))
            });
            let expected_status = operation
                .responses
                .iter()
                .filter_map(|response| response.status.parse::<u16>().ok())
                .filter(|status| (200..300).contains(status))
                .min()
                .unwrap_or(200);
            json!({
                "id": operation.id,
                "method": operation.method.as_str(),
                "path": path,
                "headers": operation.header_params.iter().filter(|(_, required)| *required)
                    .map(|(name, _)| (name.clone(), Value::String("value".to_string())))
                    .chain(operation.request_content_type.iter().map(|content_type| {
                        ("Content-Type".to_string(), Value::String(content_type.clone()))
                    }))
                    .collect::<serde_json::Map<String, Value>>(),
                "body": body,
                "expectedStatus": expected_status,
                "safe": matches!(operation.method, Method::Get | Method::Head | Method::Options),
            })
        })
        .collect::<Vec<_>>();

    write_json(&directory.join("operations.json"), &operations)?;
    std::fs::write(directory.join("k6.js"), K6_SCRIPT)
        .map_err(|error| format!("cannot write k6.js: {error}"))?;
    std::fs::write(directory.join("README.md"), K6_README)
        .map_err(|error| format!("cannot write performance README: {error}"))?;
    write_manifest(directory, spec, OpenApiSuiteKind::K6, &[])?;
    Ok((4, spec.operations.len(), Vec::new()))
}

fn write_manifest(
    directory: &Path,
    spec: &ParsedSpec,
    kind: OpenApiSuiteKind,
    warnings: &[String],
) -> Result<(), String> {
    write_json(
        &directory.join("manifest.json"),
        &json!({
            "generator": "forge-openapi",
            "kind": kind.label(),
            "title": spec.title,
            "version": spec.version,
            "operations": spec.operations.len(),
            "warnings": warnings,
        }),
    )
}

fn write_json(path: &Path, value: &impl serde::Serialize) -> Result<(), String> {
    let mut text = serde_json::to_string_pretty(value).map_err(|error| error.to_string())?;
    text.push('\n');
    std::fs::write(path, text).map_err(|error| format!("cannot write {}: {error}", path.display()))
}

fn project_relative(root: &Path, path: &Path) -> Result<String, String> {
    path.strip_prefix(root)
        .map(|path| {
            path.components()
                .map(|component| component.as_os_str().to_string_lossy())
                .collect::<Vec<_>>()
                .join("/")
        })
        .map_err(|_| format!("{} is outside project", path.display()))
}

fn base_url(spec: &ParsedSpec) -> String {
    spec.servers
        .iter()
        .find(|server| server.starts_with("http://") || server.starts_with("https://"))
        .cloned()
        .unwrap_or_else(|| "http://localhost:3000".to_string())
        .trim_end_matches('/')
        .to_string()
}

fn slug(value: &str) -> String {
    let mut out = String::new();
    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_lowercase());
        } else if !out.is_empty() && !out.ends_with('-') {
            out.push('-');
        }
    }
    out.trim_matches('-').to_string()
}

fn has_external_ref(value: &Value) -> bool {
    match value {
        Value::Object(map) => {
            map.get("$ref")
                .and_then(Value::as_str)
                .is_some_and(|reference| !reference.starts_with('#'))
                || map.values().any(has_external_ref)
        }
        Value::Array(values) => values.iter().any(has_external_ref),
        _ => false,
    }
}

const K6_SCRIPT: &str = r#"import http from 'k6/http';
import { check, sleep } from 'k6';

const operations = JSON.parse(open('./operations.json'));
const profile = __ENV.PROFILE || 'load';
const profiles = {
  smoke: { vus: 1, duration: '30s' },
  load: { stages: [{ duration: '1m', target: 10 }, { duration: '3m', target: 10 }, { duration: '1m', target: 0 }] },
  stress: { stages: [{ duration: '2m', target: 25 }, { duration: '3m', target: 50 }, { duration: '2m', target: 0 }] },
  spike: { stages: [{ duration: '15s', target: 100 }, { duration: '1m', target: 100 }, { duration: '15s', target: 0 }] },
  soak: { vus: 10, duration: '30m' },
};

export const options = {
  ...(profiles[profile] || profiles.load),
  thresholds: { http_req_failed: ['rate<0.01'], http_req_duration: ['p(95)<500'] },
};

export default function () {
  const enabled = operations.filter((operation) => operation.safe || __ENV.INCLUDE_MUTATIONS === 'true');
  if (!enabled.length) throw new Error('No safe OpenAPI operations found');
  const operation = enabled[Math.floor(Math.random() * enabled.length)];
  const baseUrl = (__ENV.BASE_URL || 'http://localhost:3000').replace(/\/$/, '');
  const response = http.request(
    operation.method,
    `${baseUrl}${operation.path}`,
    operation.body == null ? null : JSON.stringify(operation.body),
    { headers: operation.headers, tags: { operation: operation.id } },
  );
  check(response, { [`${operation.id}: status ${operation.expectedStatus}`]: (r) => r.status === operation.expectedStatus });
  sleep(Number(__ENV.SLEEP_SECONDS || 1));
}
"#;

const K6_README: &str = r#"# Generated k6 suite

Run from this directory:

```sh
k6 run -e BASE_URL=https://api.example.com -e PROFILE=load k6.js
```

Profiles: `smoke`, `load`, `stress`, `spike`, `soak`. Only GET, HEAD and OPTIONS run by default. Add `-e INCLUDE_MUTATIONS=true` only against disposable test data.
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::openapi::parse_spec;

    fn spec() -> ParsedSpec {
        parse_spec(
            r#"{
              "openapi":"3.0.3","info":{"title":"Pets","version":"1"},
              "servers":[{"url":"https://api.example.test/v1"}],
              "paths":{
                "/pets":{"get":{"operationId":"listPets","responses":{"200":{"content":{"application/json":{"schema":{"type":"array","items":{"type":"string"}}}}}}}},
                "/pets/{id}":{"parameters":[{"name":"id","in":"path","required":true,"schema":{"type":"integer"}}],"delete":{"operationId":"deletePet","responses":{"204":{"description":"deleted"}}}}
              }
            }"#,
        )
        .unwrap()
    }

    #[test]
    fn generates_runnable_forge_and_safe_k6_suites() {
        let project = tempfile::tempdir().unwrap();
        let parent = project.path().join("requests/story");
        std::fs::create_dir_all(&parent).unwrap();

        let api = generate_openapi_suite(project.path(), &parent, &spec(), OpenApiSuiteKind::Api)
            .unwrap();
        assert_eq!(api.requests, 2);
        let request = parent.join("api/get-listpets.request.json");
        let document = super::super::model::RequestDocument::parse(
            &std::fs::read_to_string(&request).unwrap(),
        )
        .unwrap();
        assert!(document.pipeline.is_empty());
        assert!(super::super::assertions::assertions_path(&request).is_file());
        assert!(parent.join("api/api.sequence.json").is_file());

        let contract =
            generate_openapi_suite(project.path(), &parent, &spec(), OpenApiSuiteKind::Contract)
                .unwrap();
        assert_eq!(contract.requests, 2);
        assert!(parent.join("contract/contract.sequence.json").is_file());

        let k6 =
            generate_openapi_suite(project.path(), &parent, &spec(), OpenApiSuiteKind::K6).unwrap();
        assert_eq!(k6.requests, 2);
        let script = std::fs::read_to_string(parent.join("performance/k6.js")).unwrap();
        assert!(script.contains("INCLUDE_MUTATIONS"));
        assert!(script.contains("stress"));

        generate_openapi_suite(project.path(), &parent, &spec(), OpenApiSuiteKind::K6).unwrap();
        let foreign_parent = project.path().join("requests/foreign");
        std::fs::create_dir_all(foreign_parent.join("contract")).unwrap();
        std::fs::write(foreign_parent.join("contract/custom.txt"), "keep").unwrap();
        assert!(generate_openapi_suite(
            project.path(),
            &foreign_parent,
            &spec(),
            OpenApiSuiteKind::Contract,
        )
        .is_err());
    }
}
